{-  OPTIONS_GHC -F -pgmF check-discover -optF --in-place -}
-- GENERATED BY check-discover
{-# LANGUAGE FlexibleInstances #-}

module Main (main, mkTests) where

import Data.String (fromString)
import Prelude
import qualified DiscoverTest
import qualified Test.Check.Core as T
import qualified Test.Check.Hedgehog as H

{- HLINT ignore "Use let" -}


mkTests :: IO T.Group
mkTests = do
  t0 <- pure $ H.testPropertyNamed "addition" (fromString "DiscoverTest.hprop_addition") DiscoverTest.hprop_addition

  pure $ T.groupBranchNamed "test/Driver.hs" [t0]

main :: IO ()
main = do
  mkTests >>= T.runGroup

